#!/bin/bash

shell_interpreter="com.github.narms.lambda.Test"
file_interpreter="com.github.narms.lambda.frontend.FileParser"

function usage() { #usage: usage
  echo "usage: ./lambda [filename]"
}

function run_shell(){ #usage: run_shell
  java -cp classes $shell_interpreter
}

function run_file(){ #usage: run_file filename
  java -cp classes $file_interpreter $1
}

if [[ $# -eq 1 ]]; then
  run_file $1
  exit 0
else
  if [[ $# -eq 0 ]]; then
    run_shell
    exit 0
  else
    echo $(usage)
    exit 1
  fi
fi
