#!/bin/bash

shell_interpreter="com.github.narms.lambda.frontend.ShellParser"
file_interpreter="com.github.narms.lambda.frontend.FileParser"
continue_on_error="-g"
#-g signifies that program execution will continue after errors

function usage() { #usage: usage
  echo "usage: ./lambda filename <heapsize>"
}

function run_file(){ #usage: run_file filename heapsize
  check_build "./vm/main/main"
  ./vm/main/main $1 $2
}

function check_build(){ #main file
  if [[ ! -f $1 ]]; then
    echo "building"
    cd vm/main
    go build
  fi
}

case $# in
  0)
    check_build ./vm/main/main
    exit 0
    ;;
  1)
    run_file $1 100
    ;;
  2)
    run_file $1 $2
    ;;
  *)
    echo $(usage)
    exit 1
    ;;
esac
